# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'param_input.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.columnView_2 = QtWidgets.QColumnView(self.centralwidget)
        self.columnView_2.setGeometry(QtCore.QRect(170, 10, 621, 551))
        self.columnView_2.setObjectName("columnView_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 20, 101, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 41, 16))
        self.label_2.setObjectName("label_2")
        self.le_lpp = QtWidgets.QLineEdit(self.centralwidget)
        self.le_lpp.setGeometry(QtCore.QRect(80, 60, 81, 20))
        self.le_lpp.setObjectName("le_lpp")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 90, 41, 16))
        self.label_3.setObjectName("label_3")
        self.le_b = QtWidgets.QLineEdit(self.centralwidget)
        self.le_b.setGeometry(QtCore.QRect(80, 90, 81, 20))
        self.le_b.setObjectName("le_b")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 120, 41, 16))
        self.label_4.setObjectName("label_4")
        self.le_d = QtWidgets.QLineEdit(self.centralwidget)
        self.le_d.setGeometry(QtCore.QRect(80, 120, 81, 20))
        self.le_d.setObjectName("le_d")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 150, 41, 9))
        self.label_5.setObjectName("label_5")
        self.le_t = QtWidgets.QLineEdit(self.centralwidget)
        self.le_t.setGeometry(QtCore.QRect(80, 150, 81, 20))
        self.le_t.setObjectName("le_t")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 180, 51, 21))
        self.label_6.setObjectName("label_6")
        self.le_delta = QtWidgets.QLineEdit(self.centralwidget)
        self.le_delta.setGeometry(QtCore.QRect(80, 180, 81, 20))
        self.le_delta.setObjectName("le_delta")
        self.btn_confirm = QtWidgets.QPushButton(self.centralwidget)
        self.btn_confirm.setGeometry(QtCore.QRect(90, 220, 56, 17))
        self.btn_confirm.setObjectName("btn_confirm")
        self.btn_reset = QtWidgets.QPushButton(self.centralwidget)
        self.btn_reset.setGeometry(QtCore.QRect(10, 220, 56, 17))
        self.btn_reset.setObjectName("btn_reset")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">船舶设计系统</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">船长（m）</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">船宽（m）</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">型深（m）</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">吃水（m）</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">排水量（t）</span></p></body></html>"))
        self.btn_confirm.setText(_translate("MainWindow", "确定"))
        self.btn_reset.setText(_translate("MainWindow", "重置"))
